import Foundation

func printUsage() {
    print("""
    jcloud — CLI for jsoneditoronline.org API and channel management

    Usage:
      jcloud doc create <name> <content>    Create document, print ID
      jcloud doc read <id>                  Read document content
      jcloud doc update <id> <content>      Update document content
      jcloud doc delete <id>                Delete document

      jcloud channel create                 Create shared channel
      jcloud channel set <id>               Set channel ID locally
      jcloud channel show                   Show current channel ID
      jcloud channel clear                  Clear local channel
      jcloud channel slot-get <slot>        Get slot value from channel
      jcloud channel slot-set <slot> <id>   Set slot value in channel

    Flags:
      -v, --version      Show version
    """)
}

let version = "1.0.0"

guard CommandLine.arguments.count >= 2 else {
    printUsage()
    exit(1)
}

// Check for flags
for arg in CommandLine.arguments.dropFirst() {
    if arg == "--version" || arg == "-v" {
        print("jcloud \(version)")
        exit(0)
    }
    if arg == "--completions",
       let idx = CommandLine.arguments.firstIndex(of: "--completions"),
       CommandLine.arguments.count > idx + 1,
       CommandLine.arguments[idx + 1] == "zsh" {
        print("""
        #compdef jcloud
        # Generated by jcloud \(version)
        _jcloud() {
            local -a commands
            commands=(
                'doc:Document operations (create/read/update/delete)'
                'channel:Channel management (create/set/show/clear/slot-get/slot-set)'
            )
            _arguments -C \\
                '(-v --version)'{-v,--version}'[Show version]' \\
                '--completions[Generate shell completions]' \\
                '1:command:->cmd' \\
                '*::arg:->args'
            case $state in
                cmd)
                    _describe 'command' commands
                    ;;
                args)
                    case $words[1] in
                        doc)
                            local -a doc_commands
                            doc_commands=(
                                'create:Create document'
                                'read:Read document'
                                'update:Update document'
                                'delete:Delete document'
                            )
                            _arguments '1:subcommand:->subcmd' '*::arg:->docargs'
                            case $state in
                                subcmd) _describe 'doc command' doc_commands ;;
                            esac
                            ;;
                        channel)
                            local -a ch_commands
                            ch_commands=(
                                'create:Create shared channel'
                                'set:Set channel ID'
                                'show:Show channel ID'
                                'clear:Clear channel'
                                'slot-get:Get slot value'
                                'slot-set:Set slot value'
                            )
                            _arguments '1:subcommand:->subcmd' '*::arg:->chargs'
                            case $state in
                                subcmd) _describe 'channel command' ch_commands ;;
                            esac
                            ;;
                    esac
                    ;;
            esac
        }
        compdef _jcloud jcloud
        """)
        exit(0)
    }
}

let command = CommandLine.arguments[1]
let args = Array(CommandLine.arguments.dropFirst(2))

do {
    switch command {
    case "doc":
        guard !args.isEmpty else {
            printUsage()
            exit(1)
        }
        switch args[0] {
        case "create":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud doc create <name> <content>")
            }
            let id = try JsonEditorAPI.create(name: args[1], content: args[2])
            print(id)

        case "read":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud doc read <id>")
            }
            let content = try JsonEditorAPI.read(id: args[1])
            print(content)

        case "update":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud doc update <id> <content>")
            }
            try JsonEditorAPI.update(id: args[1], content: args[2])

        case "delete":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud doc delete <id>")
            }
            try JsonEditorAPI.delete(id: args[1])

        default:
            printUsage()
            exit(1)
        }

    case "channel":
        guard !args.isEmpty else {
            printUsage()
            exit(1)
        }
        switch args[0] {
        case "create":
            let id = try Channel.create()
            print("Channel created: \(id)")
            print("Saved to ~/.config/b2c-gsync/channel")

        case "set":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud channel set <id>")
            }
            try Channel.writeLocal(args[1])
            print("Channel set: \(args[1])")

        case "show":
            if let id = Channel.readLocal() {
                print(id)
            } else {
                print("No channel configured.")
            }

        case "clear":
            try Channel.clearLocal()
            print("Channel cleared.")

        case "slot-get":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud channel slot-get <slot>")
            }
            let value = try Channel.getSlot(args[1])
            print(value)

        case "slot-set":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud channel slot-set <slot> <id>")
            }
            try Channel.updateSlot(args[1], id: args[2])
            print("Slot '\(args[1])' updated.")

        default:
            printUsage()
            exit(1)
        }

    default:
        printUsage()
        exit(1)
    }
} catch {
    fputs("Error: \(error.localizedDescription)\n", stderr)
    exit(1)
}
