import Foundation

func printUsage() {
    print("""
    jcloud — CLI for jsoneditoronline.org API and channel management

    Usage:
      jcloud doc create <name> <content>    Create document, print ID
      jcloud doc read <id>                  Read document content
      jcloud doc update <id> <content>      Update document content
      jcloud doc delete <id>                Delete document

      jcloud channel create                 Create shared channel
      jcloud channel set <id>               Set channel ID locally
      jcloud channel show                   Show current channel ID
      jcloud channel clear                  Clear local channel
      jcloud channel slot-get <slot>        Get slot value from channel
      jcloud channel slot-set <slot> <id>   Set slot value in channel

      jcloud backup [file]                  Export channel data to file (default: stdout)
      jcloud restore <file>                 Import channel data from file

    Flags for slot-set:
      --tool <name>           Tool name to track version
      --tool-version <ver>    Tool version to record

    Flags for slot-get:
      --check-tools <n:v,...>  Check tool versions against channel

    Flags:
      -v, --version      Show version
    """)
}

let version = "1.3.0"

guard CommandLine.arguments.count >= 2 else {
    printUsage()
    exit(1)
}

// Check for flags
for arg in CommandLine.arguments.dropFirst() {
    if arg == "--version" || arg == "-v" {
        print("jcloud \(version)")
        exit(0)
    }
    if arg == "--completions",
       let idx = CommandLine.arguments.firstIndex(of: "--completions"),
       CommandLine.arguments.count > idx + 1,
       CommandLine.arguments[idx + 1] == "zsh" {
        print("""
        #compdef jcloud
        # Generated by jcloud \(version)
        _jcloud() {
            local -a commands
            commands=(
                'doc:Document operations (create/read/update/delete)'
                'channel:Channel management (create/set/show/clear/slot-get/slot-set)'
                'publish:Upload binaries to channel'
                'update:Download and install updated binaries'
            )
            _arguments -C \\
                '(-v --version)'{-v,--version}'[Show version]' \\
                '--completions[Generate shell completions]' \\
                '1:command:->cmd' \\
                '*::arg:->args'
            case $state in
                cmd)
                    _describe 'command' commands
                    ;;
                args)
                    case $words[1] in
                        doc)
                            local -a doc_commands
                            doc_commands=(
                                'create:Create document'
                                'read:Read document'
                                'update:Update document'
                                'delete:Delete document'
                            )
                            _arguments '1:subcommand:->subcmd' '*::arg:->docargs'
                            case $state in
                                subcmd) _describe 'doc command' doc_commands ;;
                            esac
                            ;;
                        channel)
                            local -a ch_commands
                            ch_commands=(
                                'create:Create shared channel'
                                'set:Set channel ID'
                                'show:Show channel ID'
                                'clear:Clear channel'
                                'slot-get:Get slot value'
                                'slot-set:Set slot value'
                            )
                            _arguments '1:subcommand:->subcmd' '*::arg:->chargs'
                            case $state in
                                subcmd) _describe 'channel command' ch_commands ;;
                            esac
                            ;;
                        publish)
                            _arguments '*:tool name:(b2c gsync jcloud)'
                            ;;
                    esac
                    ;;
            esac
        }
        compdef _jcloud jcloud
        """)
        exit(0)
    }
}

let command = CommandLine.arguments[1]
let args = Array(CommandLine.arguments.dropFirst(2))

// Helper to extract flag value from args
func flagValue(_ flag: String, in arguments: [String]) -> String? {
    guard let idx = arguments.firstIndex(of: flag), idx + 1 < arguments.count else {
        return nil
    }
    return arguments[idx + 1]
}

do {
    switch command {
    case "doc":
        guard !args.isEmpty else {
            printUsage()
            exit(1)
        }
        switch args[0] {
        case "create":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud doc create <name> <content>")
            }
            let id = try JsonEditorAPI.create(name: args[1], content: args[2])
            print(id)

        case "read":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud doc read <id>")
            }
            let content = try JsonEditorAPI.read(id: args[1])
            print(content)

        case "update":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud doc update <id> <content>")
            }
            try JsonEditorAPI.update(id: args[1], content: args[2])

        case "delete":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud doc delete <id>")
            }
            try JsonEditorAPI.delete(id: args[1])

        default:
            printUsage()
            exit(1)
        }

    case "channel":
        guard !args.isEmpty else {
            printUsage()
            exit(1)
        }
        switch args[0] {
        case "create":
            let interactive = args.contains("--interactive")
            let reply = flagValue("--reply", in: args)

            if interactive {
                if let reply {
                    // Phase 2: complete with user's answer
                    if reply == "replace" {
                        let id = try Channel.create()
                        InteractiveProtocol.outputDone(message: "Channel created: \(id)")
                    } else {
                        InteractiveProtocol.outputDone(message: "Cancelled")
                    }
                } else {
                    // Phase 1: check state, return prompt or done
                    if let existing = Channel.readLocal() {
                        let taskId = UUID().uuidString
                        InteractiveProtocol.saveCache(taskId: taskId, data: ["existing": existing])
                        InteractiveProtocol.outputPrompt(
                            taskId: taskId,
                            title: "Channel exists: \(existing)",
                            type: "select",
                            options: [
                                .init(value: "replace", label: "Yes, replace it"),
                                .init(value: "keep", label: "No, keep current"),
                            ]
                        )
                    } else {
                        let id = try Channel.create()
                        InteractiveProtocol.outputDone(message: "Channel created: \(id)")
                    }
                }
            } else {
                // Direct mode (no --interactive)
                let id = try Channel.create()
                print("Channel created: \(id)")
                print("Saved to ~/.config/b2c-gsync/channel")
            }

        case "set":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud channel set <id>")
            }
            try Channel.writeLocal(args[1])
            print("Channel set: \(args[1])")

        case "show":
            if let id = Channel.readLocal() {
                print(id)
            } else {
                print("No channel configured.")
            }

        case "clear":
            let interactive = args.contains("--interactive")
            let reply = flagValue("--reply", in: args)

            if interactive {
                if let reply {
                    if reply == "clear" {
                        try Channel.clearLocal()
                        InteractiveProtocol.outputDone(message: "Channel cleared")
                    } else {
                        InteractiveProtocol.outputDone(message: "Cancelled")
                    }
                } else {
                    if let existing = Channel.readLocal() {
                        let taskId = UUID().uuidString
                        InteractiveProtocol.saveCache(taskId: taskId, data: ["existing": existing])
                        InteractiveProtocol.outputPrompt(
                            taskId: taskId,
                            title: "Clear channel: \(existing)?",
                            type: "select",
                            options: [
                                .init(value: "clear", label: "Yes, clear it"),
                                .init(value: "keep", label: "No, keep it"),
                            ]
                        )
                    } else {
                        InteractiveProtocol.outputDone(message: "No channel configured")
                    }
                }
            } else {
                try Channel.clearLocal()
                print("Channel cleared.")
            }

        case "slot-get":
            guard args.count >= 2 else {
                throw JCloudError.missingArgument("Usage: jcloud channel slot-get <slot>")
            }
            // Read channel once for both slot value and version check
            let channel = try Channel.readRemote()
            guard let entry = channel.slots[args[1]] else {
                throw JCloudError.noSlotInChannel(args[1])
            }
            print(entry.id)

            // Check tool versions if requested
            if let checkSpec = flagValue("--check-tools", in: args) {
                let channelVersions = channel.versions ?? [:]

                var fullSpec = checkSpec
                fullSpec += ",jcloud:\(version)"

                let outdated = Channel.checkTools(fullSpec, channelVersions: channelVersions)
                if !outdated.isEmpty {
                    let toolNames = outdated.map { $0.0 }.joined(separator: " ")
                    fputs("\n⚠ Outdated tools:\n", stderr)
                    for (name, local, remote) in outdated {
                        fputs("  \(name)  local: \(local)  channel: \(remote)\n", stderr)
                    }
                    fputs("On the other machine run: seed publish \(toolNames)\n", stderr)
                    fputs("Then on this machine run: seed update\n", stderr)
                }
            }

        case "slot-set":
            guard args.count >= 3 else {
                throw JCloudError.missingArgument("Usage: jcloud channel slot-set <slot> <id>")
            }
            let toolName = flagValue("--tool", in: args)
            let toolVersion = flagValue("--tool-version", in: args)

            try Channel.updateSlot(
                args[1], id: args[2],
                toolName: toolName, toolVersion: toolVersion,
                extraVersions: ["jcloud": version]
            )
            print("Slot '\(args[1])' updated.")

        default:
            printUsage()
            exit(1)
        }

    case "publish":
        fputs("publish has moved to seed. Run: seed publish <tool1> [tool2] ...\n", stderr)
        exit(1)

    case "update":
        fputs("update has moved to seed. Run: seed update\n", stderr)
        exit(1)

    case "backup":
        let channel = try Channel.readRemote()
        guard let json = String(data: try JSONEncoder().encode(channel), encoding: .utf8) else {
            throw JCloudError.invalidResponse
        }
        if !args.isEmpty {
            try json.write(toFile: args[0], atomically: true, encoding: .utf8)
            print("Channel backed up to: \(args[0])")
        } else {
            print(json)
        }

    case "restore":
        guard !args.isEmpty else {
            throw JCloudError.missingArgument("Usage: jcloud restore <file>")
        }
        let content = try String(contentsOfFile: args[0], encoding: .utf8)
        // Validate JSON
        guard let data = content.data(using: .utf8),
              let _ = try? JSONDecoder().decode(ChannelData.self, from: data) else {
            throw JCloudError.invalidChannel
        }
        guard let channelId = Channel.readLocal() else {
            throw JCloudError.noChannel
        }
        try JsonEditorAPI.update(id: channelId, content: content)
        print("Channel restored from: \(args[0])")

    default:
        printUsage()
        exit(1)
    }
} catch {
    fputs("Error: \(error.localizedDescription)\n", stderr)
    exit(1)
}
